# stock-api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: stock-api # DNS name for other services to use
  labels:
    app: stock-api
spec:
  type: ClusterIP
  selector:
    app: stock-api # Matches the labels of the Pods in stock-api-deployment
  ports:
  - protocol: TCP
    port: 80 # Port the service will be available on
    targetPort: 8080 # Port on the Pods (must match containerPort in deployment) <-- VERIFY THIS
